os: linux
sudo: required
language: "minimal"
services:
  - docker
env:
  - ID='timenergy' IMG='bootstrap-cpp'

before_script:
  - docker pull $ID/$IMG
  - chmod +x -R ./scripts

jobs:
  include:
    - name: "compile"
      script:
        - docker run -t -v $(pwd):/var/builder/ -w /var/builder --entrypoint ./scripts/compile.sh $ID/$IMG

notifications:
  email: false
